name: veloce-sfdx
on: [push]
jobs:
  unit-test:
    runs-on: node:latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: |
          yarn install
          yarn prepack
          yarn test
          ./node_modules/.bin/nyc report --reporter text-lcov > coverage.lcov
          curl -s https://codecov.io/bash | bash
